apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-examples
  namespace: argo
spec:
  goTemplate: true
  goTemplateOptions: ['missingkey=error']
  generators:
    - list:
        elements:
          - name: app
          - name: bucket
  template:
    metadata:
      name: '{{.name}}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: '.;..'
    spec:
      project: default
      source:
        repoURL: https://github.com/sule26/devopsboost.git
        targetRevision: HEAD
        path: examples/{{.name}}
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - SkipDryRunOnMissingResource=true
