apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: color-demo
  template:
    metadata:
      labels:
        app: color-demo
    spec:
      containers:
        - name: color
          image: jpetazzo/color:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: color-demo
spec:
  selector:
    app: color-demo
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: color-demo-ingress
  annotations:
    external-dns.alpha.kubernetes.io/hostname: web.sule.live
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - web.sule.live
      secretName: color-demo-tls
  rules:
    - host: web.sule.live
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: color-demo
                port:
                  number: 80
